apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  namespace: default
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "classschedule"
  POSTGRES_PASSWORD: "passpass"
  PGDATA: "/var/lib/postgresql/data/dbfiles"
